### ISSUE TITLE
4.2.1 Compatibility

### ISSUE THREAD

**Issue by brian428** [EirikLorentsen/Ext.ux.window.Notification#1]
For me, under 4.2.1 the x and y positions of the window don't seem to be getting set before the animation runs. I had to add this at line 357:

me.x = me.getX();
me.y = me.getY();

**Comment by brian428** [comment]
Ah, I see from the forum that you weren't able to replicate this. Hmmm...I'll see if I can come up with a test (I ran into it in a live app so I'd have to build up a test from scratch). That said, since I don't think there's any negative consequence from adding those two lines...might be worth just doing it? Can you think of any reason that would cause a problem? Thanks.

**Comment by EirikLorentsen** [comment]
I can't think of any reason it would do any harm. But if a hack can be avoided by writing better code it is always better.

Would it be possible for you to try moving line 369: this.callParent(arguments); up to 357 instead of setting x and y in the live app? Maybe the callParent() must be called before the animation can be run.

Btw: Is the live app using the cdn version of 4.2.1 or a downloaded copy? Could there be any difference in the two? (I'm testing on the cdn.sencha.com version)

**Comment by brian428** [comment]
I was testing on the downloaded 4.2.1, but AFAIK there should be no difference between them other than the license text. I'll try making the change, taking out my change, and see what happens. Thanks.

**Comment by brian428** [comment]
Actually, just FYI, I now recall that I tried it on both a downloaded copy and the CDN version, with the same results.

**Comment by EirikLorentsen** [comment]
I ran a test and saw the x and y properties on the component corresponding to a placement in the center of the viewport. The placement of callParent did not affect this and would therefore not offer a solution.

I then tested setting me.x with me.getX(), but getting the x coordinate directly from the component appears to be a relatively new feature. I had to use me.el.getX() instead, or else it would throw an error with Ext v4.0.7.

Also to increase readability I placed the calls in the config for the animate function. It felt better doing this instead of changing a property in the notification's config halfway in the show process.
