### ISSUE TITLE
OPTION: Destroy notification window on hide

### ISSUE THREAD

**Issue by anotheri** [EirikLorentsen/Ext.ux.window.Notification#2]
First, thanks for useful user extension! It save a lot of time for me!

I just want to note that all notification windows is not destroyed after hiding ones. Its still present in the DOM even when we don't see it.

Of courese anyone (and me too) can use listeners, e.g.:

```
Ext.create('widget.uxNotification', {
    position: 't',
    closable: false,
    title: 'Title',
    html: 'Notification body',

    // important part of code ->
    listeners: {
        'hide': function(wnd) {
            wnd.destroy();
        }
    }
    // <- important part of code

}).show();
```

But I think for usability will be better if you add just an option for this behaviour.

**Comment by EirikLorentsen** [comment]
Thanx for the feedback!

This was a regression caused by some simplification I did in previous versions.
A Notification is an Ext.window which means it should respect the closeAction parameter when being closed and either 'hide' or 'destroy' accordingly.

With the latest bugfix the DOM is again destroyed as it should.
Unless closeAction is set to 'hide'. There is an example on the demo page with closeAction set to 'hide'.
