### ISSUE TITLE
Notification doesn't go away automatically if I highlight and unhighlight text after

### ISSUE THREAD

**Issue by choweiyuan** [EirikLorentsen/Ext.ux.window.Notification#5]
So I was highlighting the text in the notification window, can simply try any of the examples here 
http://www.eirik.net/Ext/ux/window/Demo.html.

Then, I unhighlight my text, it doesn't go away, I have to click the close button manually. 
Potentially unclosable if user defined the window's "closable" property to false.

![highlight](https://cloud.githubusercontent.com/assets/4201614/5577867/7cc9007c-9012-11e4-8edf-cfb51cae2bc6.PNG)

**Comment by EirikLorentsen** [comment]
This is actually intentional. There is a specific property called stickOnClick that enables this behavior, and it is enabled by default.

By setting stickOnClick to false the notification will not "stick" after being clicked on.

The demo page has an example called "BL - stickOnClick" where this property is set to false. Even if the text in the notification is selected that notification disappears anyway.

**Comment by choweiyuan** [comment]
Sorry for not checking examples thoroughly. Thanks for pointing that out!
